import SwiftUI

/// Replaces the old single-agent Claude tab. The list on the left is both the agent
/// registry and the shortcut binding — row 1 is ⌘N, row 2 ⌘⇧N, row 3 ⌘⇧⌥N — so the shortcut
/// is shown inline on each row rather than hidden in a help string. Dragging a row is what
/// rebinds ⌘N: see `Preferences.moveAgents` and `NewSessionAffordance`.
struct AgentsSettingsTab: View {
    @ObservedObject var preferences: PreferencesStore
    @State private var selection: AgentID?

    var body: some View {
        HSplitView {
            List(selection: $selection) {
                ForEach(preferences.preferences.agents, id: \.id) { settings in
                    HStack {
                        Text(settings.id.displayName)
                        Spacer()
                        Text(shortcut(for: settings.id))
                            .foregroundStyle(.secondary)
                            .monospaced()
                    }
                    .tag(settings.id)
                }
                .onMove { offsets, destination in
                    preferences.preferences.moveAgents(fromOffsets: offsets, toOffset: destination)
                }
            }
            .frame(minWidth: 160)

            Group {
                switch selection ?? preferences.preferences.agents.first?.id {
                case .codex: CodexOptionsForm(preferences: preferences)
                default:     ClaudeOptionsPane(preferences: preferences)
                }
            }
            .frame(minWidth: 380)
        }
    }

    private func shortcut(for agent: AgentID) -> String {
        NewSessionAffordance.slots(for: preferences.preferences.agents)
            .first { $0.agent == agent }?.shortcutDisplay ?? ""
    }
}

/// Global defaults: the flags every new session starts with, in every project.
///
/// Formerly `ClaudeSettingsTab`, the app's only Preferences tab before agent adapters — this
/// is that same body, moved under the Agents list's claude row. Deliberately still bound to
/// `globalFlags` rather than the claude entry's `AgentOptions` in `preferences.agents`:
/// `SessionStore.options(for:project:)` resolves a launch's flags from `globalFlags` (via
/// `PreferencesStore.resolvedFlags`), and repointing this pane at the list entry instead
/// would edit a value nothing reads while leaving the one that matters untouched.
struct ClaudeOptionsPane: View {
    @ObservedObject var preferences: PreferencesStore

    var body: some View {
        FlagEditor(
            flags: $preferences.preferences.globalFlags,
            inherited: nil,
            lockedPrefix: Self.placeholderPrefix,
            header: {
                AnyView(
                    Section("Startup") {
                        Toggle(
                            "Auto-resume running sessions on restart",
                            isOn: Binding(
                                get: { preferences.autoResumesRunningSessions },
                                set: { preferences.autoResumesRunningSessions = $0 }
                            )
                        )
                        .accessibilityIdentifier("prefs-auto-resume")
                        // States the busy/shell rule in the user's terms: "running" is not
                        // self-evident from the label, and the exclusions are the surprising
                        // half.
                        Text("Sessions that were working when Flight Deck last quit are asked to continue once they have resumed. Sessions that were idle, or waiting on you, are left alone.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                )
            }
        )
    }

    /// There is no real session in the global tab, so the immutable prefix shows what
    /// Flight Deck will substitute rather than a concrete id and name. Deliberately not
    /// generated by calling `ClaudeSession.lockedPrefix` with sentinel values — that would
    /// route the placeholder text through `sanitizedName`/`shellQuoted` and render as
    /// `--name '⟨session title⟩'`, which is worse. Nothing else keeps this in step with
    /// `lockedPrefix`'s actual flag sequence, so
    /// `ClaudeSessionTests.testPlaceholderPrefixMatchesTheRealPrefixShape` pins the shape.
    static let placeholderPrefix = "claude --session-id ⟨generated⟩ --name ⟨session title⟩"
}
