import SwiftUI

/// Global defaults: the flags every new session starts with, in every project.
struct ClaudeSettingsTab: View {
    @ObservedObject var preferences: PreferencesStore

    var body: some View {
        FlagEditor(
            flags: $preferences.preferences.globalFlags,
            inherited: nil,
            lockedPrefix: Self.placeholderPrefix,
            header: {
                AnyView(
                    Section("Startup") {
                        Toggle(
                            "Auto-resume running sessions on restart",
                            isOn: Binding(
                                get: { preferences.autoResumesRunningSessions },
                                set: { preferences.autoResumesRunningSessions = $0 }
                            )
                        )
                        .accessibilityIdentifier("prefs-auto-resume")
                        // States the busy/shell rule in the user's terms: "running" is not
                        // self-evident from the label, and the exclusions are the surprising
                        // half.
                        Text("Sessions that were working when Flight Deck last quit are asked to continue once they have resumed. Sessions that were idle, or waiting on you, are left alone.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                )
            }
        )
    }

    /// There is no real session in the global tab, so the immutable prefix shows what
    /// Flight Deck will substitute rather than a concrete id and name. Deliberately not
    /// generated by calling `ClaudeSession.lockedPrefix` with sentinel values — that would
    /// route the placeholder text through `sanitizedName`/`shellQuoted` and render as
    /// `--name '⟨session title⟩'`, which is worse. Nothing else keeps this in step with
    /// `lockedPrefix`'s actual flag sequence, so
    /// `ClaudeSessionTests.testPlaceholderPrefixMatchesTheRealPrefixShape` pins the shape.
    static let placeholderPrefix = "claude --session-id ⟨generated⟩ --name ⟨session title⟩"
}
